spring.application.name=pnc-segundo-parcial-coworking

# Configuración de base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coworking_db
spring.datasource.username=postgres
spring.datasource.password=2012

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true.url